export const paths = {
  home: '/',
  trips: '/trips',
  login: '/login',
  register: '/register',
  forgot: '/forgot-password',
  tickets: '/account/tickets',
  passes: '/account/passes',
  notifications: '/account/notifications',
  support: '/account/support',
  profile: '/account/profile',
  admin: '/admin',
  staff: '/staff/trips',
  trip: (id: string) => '/trips/' + id,
  booking: (id: string) => '/booking/' + id,
  checkout: (id: string) => '/checkout/' + id,
  ticket: (id: string) => '/account/tickets/' + id,
  tracking: (id: string) => '/tracking/' + id,
  result: (id: string) => '/payment/result?bookingId=' + id,
};
