-- Preserve the verified-empty legacy schema already present in the target project.
-- Abort rather than move any table containing data or an unrecognized schema.
DO $$
DECLARE _tbl_name text; _row_count bigint;
BEGIN
  -- If legacy tables are already archived or modern schema exists, nothing to archive
  IF to_regclass('smartbus_legacy_20261001.routes') IS NOT NULL OR to_regclass('public.roles') IS NOT NULL THEN
    RETURN;
  END IF;

  IF to_regclass('public.routes') IS NOT NULL THEN
    IF (SELECT count(*) FROM pg_tables WHERE schemaname='public') <> 7 OR
       NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND information_schema.columns.table_name='routes' AND column_name='id' AND data_type='uuid') THEN
      RAISE EXCEPTION 'Unrecognized existing schema. Review before migration.';
    END IF;
    FOREACH _tbl_name IN ARRAY ARRAY['routes','bus_stops','route_stops','buses','trips','bookings','tickets'] LOOP
      EXECUTE format('LOCK TABLE public.%I IN ACCESS EXCLUSIVE MODE', _tbl_name);
      EXECUTE format('SELECT count(*) FROM public.%I', _tbl_name) INTO _row_count;
      IF _row_count <> 0 THEN RAISE EXCEPTION 'Existing table % is not empty', _tbl_name; END IF;
    END LOOP;
    CREATE SCHEMA smartbus_legacy_20261001;
    REVOKE ALL ON SCHEMA smartbus_legacy_20261001 FROM PUBLIC;
    FOREACH _tbl_name IN ARRAY ARRAY['routes','bus_stops','route_stops','buses','trips','bookings','tickets'] LOOP
      EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', _tbl_name);
      EXECUTE format('ALTER TABLE public.%I SET SCHEMA smartbus_legacy_20261001', _tbl_name);
      EXECUTE format('REVOKE ALL ON smartbus_legacy_20261001.%I FROM PUBLIC', _tbl_name);
      IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN EXECUTE format('REVOKE ALL ON smartbus_legacy_20261001.%I FROM anon',_tbl_name); END IF;
      IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN EXECUTE format('REVOKE ALL ON smartbus_legacy_20261001.%I FROM authenticated',_tbl_name); END IF;
    END LOOP;
  END IF;
END $$;

-- PostgreSQL schema for the deployed Express API. Existing IDs remain valid as text.
-- Intentionally fails on an existing schema; never drops production tables.

CREATE TABLE roles (

  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  description VARCHAR(255) NULL,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE users (

  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  full_name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  phone_number VARCHAR(20) NULL,
  password_hash VARCHAR(255) NOT NULL,
  role_id INT NOT NULL,
  role text CHECK (role IN ('ADMIN', 'MANAGER', 'DRIVER', 'PASSENGER')) DEFAULT 'PASSENGER',
  status text CHECK (status IN ('ACTIVE', 'INACTIVE', 'LOCKED')) DEFAULT 'ACTIVE',
  discount_type text CHECK (discount_type IN ('NONE', 'STUDENT', 'ELDERLY')) DEFAULT 'NONE',
  discount_status text CHECK (discount_status IN ('NOT_REGISTERED', 'PENDING', 'APPROVED', 'REJECTED')) DEFAULT 'NOT_REGISTERED',
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT

);

CREATE TABLE routes (

  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  code VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(150) NOT NULL,
  description TEXT NULL,
  distance_km DECIMAL(6,2) DEFAULT 0.00,
  base_price DECIMAL(10,2) DEFAULT 10000.00,
  estimated_duration_min INT DEFAULT 0,
  status text CHECK (status IN ('ACTIVE', 'INACTIVE')) DEFAULT 'ACTIVE',
  deleted_at timestamptz NULL,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE bus_stops (

  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  code VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(150) NOT NULL,
  address VARCHAR(255),
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  is_active BOOLEAN DEFAULT TRUE,
  deleted_at timestamptz NULL,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE route_stops (

  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  route_id text NOT NULL,
  stop_id text NOT NULL,
  stop_order INT NOT NULL,
  distance_from_start_km DECIMAL(6,2) DEFAULT 0.00,
  estimated_time_minutes INT DEFAULT 0,
  CONSTRAINT fk_rs_route FOREIGN KEY (route_id) REFERENCES routes(id) ON DELETE CASCADE,
  CONSTRAINT fk_rs_stop FOREIGN KEY (stop_id) REFERENCES bus_stops(id) ON DELETE CASCADE,
  CONSTRAINT uq_route_stop_order UNIQUE (route_id, stop_order)
);

CREATE TABLE buses (

  id text PRIMARY KEY,
  plate_number VARCHAR(20) NOT NULL UNIQUE,
  bus_type VARCHAR(50) DEFAULT 'STANDARD',
  total_seats INT DEFAULT 40,
  standing_capacity INT DEFAULT 15,
  status VARCHAR(50) DEFAULT 'READY',
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE seats (

  id text PRIMARY KEY,
  bus_id text NOT NULL,
  seat_number VARCHAR(10) NOT NULL,
  seat_type VARCHAR(20) DEFAULT 'STANDARD',
  row_position VARCHAR(20) DEFAULT 'WINDOW',
  deck VARCHAR(20) DEFAULT 'DECK_1',
  is_priority BOOLEAN DEFAULT FALSE,
  status VARCHAR(20) DEFAULT 'ACTIVE',
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_seats_bus FOREIGN KEY (bus_id) REFERENCES buses(id) ON DELETE CASCADE,
  CONSTRAINT uq_seats_bus_seat_number UNIQUE (bus_id, seat_number)
);

CREATE TABLE fares (

  id text PRIMARY KEY,
  route_id text NOT NULL,
  fare_type text CHECK (fare_type IN ('FLAT_FARE','STAGE_FARE')) DEFAULT 'FLAT_FARE',
  ticket_type text CHECK (ticket_type IN ('SINGLE','MONTHLY_STUDENT','MONTHLY_REGULAR','PRIORITY')) DEFAULT 'SINGLE',
  amount numeric(12,2) NOT NULL,
  is_active boolean DEFAULT TRUE,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE trips (

  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  route_id text NOT NULL,
  bus_id text REFERENCES buses(id) ON DELETE RESTRICT,
  bus_plate VARCHAR(20),
  driver_id text NULL,
  departure_time timestamptz NOT NULL,
  arrival_time timestamptz NOT NULL,
  total_seats INT DEFAULT 40,
  booked_seats INT DEFAULT 0,
  base_price DECIMAL(10,2) DEFAULT 10000.00,
  status text CHECK (status IN ('SCHEDULED', 'IN_TRANSIT', 'COMPLETED', 'CANCELLED')) DEFAULT 'SCHEDULED',
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_trips_route FOREIGN KEY (route_id) REFERENCES routes(id) ON DELETE CASCADE,
  CONSTRAINT fk_trips_driver FOREIGN KEY (driver_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE tickets (

  id text PRIMARY KEY,
  ticket_code VARCHAR(50) UNIQUE,
  trip_id text NOT NULL,
  status text CHECK (status IN ('RESERVED','BOOKED','CHECKED_IN','CANCELLED')) DEFAULT 'BOOKED',
  seat_number VARCHAR(10) NULL,
  user_id text NULL,
  fare_amount DECIMAL(10,2) DEFAULT 10000.00,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_tickets_trip FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE,
  CONSTRAINT fk_tickets_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL

);

CREATE TABLE trip_seats (

  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  trip_id text NOT NULL,
  seat_id text NULL,
  seat_number VARCHAR(10) NOT NULL,
  status text CHECK (status IN ('AVAILABLE', 'LOCKED', 'BOOKED', 'CHECKED_IN')) DEFAULT 'AVAILABLE',
  locked_at timestamptz NULL,
  locked_by_user_id text NULL,
  lock_expires_at timestamptz NULL,
  ticket_id text NULL,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_trip_seats_trip FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE,
  CONSTRAINT fk_trip_seats_seat FOREIGN KEY (seat_id) REFERENCES seats(id) ON DELETE SET NULL,
  CONSTRAINT fk_trip_seats_user FOREIGN KEY (locked_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_trip_seats_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE SET NULL,
  CONSTRAINT uq_trip_seats_trip_number UNIQUE (trip_id, seat_number)
);

CREATE TABLE incidents (

  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  trip_id text NOT NULL,
  driver_id text NULL,
  incident_type VARCHAR(50) NOT NULL,
  severity VARCHAR(20) DEFAULT 'MEDIUM',
  description TEXT NOT NULL,
  delay_minutes INT DEFAULT 0,
  action_taken TEXT NULL,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_incidents_trip FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE,
  CONSTRAINT fk_incidents_driver FOREIGN KEY (driver_id) REFERENCES users(id) ON DELETE SET NULL

);

CREATE TABLE feedbacks (

  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  trip_id text NOT NULL,
  user_id text NULL,
  rating_stars INT NOT NULL,
  criteria VARCHAR(100) NULL,
  content TEXT NOT NULL,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_feedbacks_trip FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE,
  CONSTRAINT fk_feedbacks_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL

);

CREATE INDEX idx_route_stops_order ON route_stops (route_id, stop_order);
CREATE INDEX idx_seats_bus_id ON seats (bus_id);
CREATE INDEX idx_trips_route_departure ON trips (route_id, departure_time);
CREATE INDEX idx_trip_seats_trip_status ON trip_seats (trip_id, status);
CREATE INDEX idx_trip_seats_lock_expires ON trip_seats (lock_expires_at);
CREATE UNIQUE INDEX users_email_lower ON users (lower(email));
CREATE UNIQUE INDEX users_phone_unique ON users (phone_number) WHERE phone_number IS NOT NULL;
CREATE UNIQUE INDEX tickets_active_seat ON tickets (trip_id, seat_number) WHERE status IN ('BOOKED','CHECKED_IN');
CREATE INDEX users_role_idx ON users(role_id);
CREATE INDEX route_stops_stop_idx ON route_stops(stop_id);
CREATE INDEX trips_bus_idx ON trips(bus_id);
CREATE INDEX trips_driver_idx ON trips(driver_id);
CREATE INDEX tickets_user_idx ON tickets(user_id);
CREATE INDEX trip_seats_seat_idx ON trip_seats(seat_id);
CREATE INDEX trip_seats_user_idx ON trip_seats(locked_by_user_id);
CREATE INDEX trip_seats_ticket_idx ON trip_seats(ticket_id);
CREATE INDEX incidents_trip_idx ON incidents(trip_id);
CREATE INDEX incidents_driver_idx ON incidents(driver_id);
CREATE INDEX feedbacks_trip_idx ON feedbacks(trip_id);
CREATE INDEX feedbacks_user_idx ON feedbacks(user_id);
ALTER TABLE fares ADD CONSTRAINT fares_route_fk FOREIGN KEY(route_id) REFERENCES routes(id) ON DELETE CASCADE;
CREATE INDEX fares_route_idx ON fares(route_id);
ALTER TABLE feedbacks ADD CONSTRAINT feedback_rating CHECK (rating_stars BETWEEN 1 AND 5);
ALTER TABLE buses ADD CONSTRAINT bus_capacity CHECK (total_seats > 0 AND total_seats <= 200);
ALTER TABLE trips ADD CONSTRAINT trip_times CHECK (arrival_time > departure_time);
ALTER TABLE tickets ADD CONSTRAINT ticket_fare CHECK (fare_amount >= 0);
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON roles FROM PUBLIC;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN REVOKE ALL ON roles FROM anon; END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN REVOKE ALL ON roles FROM authenticated; END IF;
END $$;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON users FROM PUBLIC;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN REVOKE ALL ON users FROM anon; END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN REVOKE ALL ON users FROM authenticated; END IF;
END $$;
ALTER TABLE routes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON routes FROM PUBLIC;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN REVOKE ALL ON routes FROM anon; END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN REVOKE ALL ON routes FROM authenticated; END IF;
END $$;
ALTER TABLE bus_stops ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON bus_stops FROM PUBLIC;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN REVOKE ALL ON bus_stops FROM anon; END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN REVOKE ALL ON bus_stops FROM authenticated; END IF;
END $$;
ALTER TABLE route_stops ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON route_stops FROM PUBLIC;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN REVOKE ALL ON route_stops FROM anon; END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN REVOKE ALL ON route_stops FROM authenticated; END IF;
END $$;
ALTER TABLE buses ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON buses FROM PUBLIC;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN REVOKE ALL ON buses FROM anon; END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN REVOKE ALL ON buses FROM authenticated; END IF;
END $$;
ALTER TABLE seats ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON seats FROM PUBLIC;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN REVOKE ALL ON seats FROM anon; END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN REVOKE ALL ON seats FROM authenticated; END IF;
END $$;
ALTER TABLE fares ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON fares FROM PUBLIC;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN REVOKE ALL ON fares FROM anon; END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN REVOKE ALL ON fares FROM authenticated; END IF;
END $$;
ALTER TABLE trips ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON trips FROM PUBLIC;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN REVOKE ALL ON trips FROM anon; END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN REVOKE ALL ON trips FROM authenticated; END IF;
END $$;
ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON tickets FROM PUBLIC;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN REVOKE ALL ON tickets FROM anon; END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN REVOKE ALL ON tickets FROM authenticated; END IF;
END $$;
ALTER TABLE trip_seats ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON trip_seats FROM PUBLIC;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN REVOKE ALL ON trip_seats FROM anon; END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN REVOKE ALL ON trip_seats FROM authenticated; END IF;
END $$;
ALTER TABLE incidents ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON incidents FROM PUBLIC;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN REVOKE ALL ON incidents FROM anon; END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN REVOKE ALL ON incidents FROM authenticated; END IF;
END $$;
ALTER TABLE feedbacks ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON feedbacks FROM PUBLIC;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN REVOKE ALL ON feedbacks FROM anon; END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN REVOKE ALL ON feedbacks FROM authenticated; END IF;
END $$;
INSERT INTO roles(id,name) VALUES (1,'ADMIN'),(2,'MANAGER'),(3,'DRIVER'),(4,'PASSENGER');
SELECT setval(pg_get_serial_sequence('roles','id'),4,true);
